/**
 * BoothApp Walkthrough - Step-by-step guided tour of session analysis output.
 * Highlights each analysis section with tooltip explanations.
 *
 * Usage: new BoothWalkthrough() — attaches to the walkthrough button in topbar.
 */
(function () {
  "use strict";

  var STEPS = [
    {
      selector: ".visitor-card",
      title: "Visitor Profile",
      body: "Badge OCR extracts the visitor's name, title, and company. The engagement score (0-10) is computed by Claude based on question depth, time spent, and interaction patterns.",
      position: "bottom"
    },
    {
      /* executive_summary is the first .summary-text inside .analysis-scroll */
      selector: ".analysis-scroll .summary-text",
      title: "Executive Summary",
      body: "Claude reads the full transcript and click timeline, then produces a concise narrative of what happened during the demo — who the visitor is, what they cared about, and how engaged they were.",
      position: "left"
    },
    {
      selector: ".analysis-scroll .interests-tbl",
      title: "Key Interests",
      body: "Each interest is extracted from conversation topics and browsing behavior. Confidence levels (High / Medium / Low) reflect how strongly the evidence supports each interest. Judges: this is what drives the personalized follow-up email.",
      position: "left"
    },
    {
      selector: ".analysis-scroll .actions-list",
      title: "Follow-up Actions",
      body: "Concrete next steps generated by Claude for the SDR team — schedule a call, send a whitepaper, connect with a specialist. These are actionable, not generic.",
      position: "left"
    },
    {
      selector: ".analysis-scroll .moment-item",
      title: "Key Moments",
      body: "Timestamps where something significant happened — a pointed question, a feature deep-dive, or a buying signal. Linked to the session timeline so you can jump to the exact screenshot.",
      position: "left"
    },
    {
      selector: ".timeline-card",
      title: "Session Timeline",
      body: "Every click the SE made during the demo, captured by our Chrome extension. Each entry has a timestamp, description, and screenshot thumbnail you can click to enlarge.",
      position: "right"
    },
    {
      selector: ".transcript-card",
      title: "Transcript",
      body: "Real-time audio transcription of the demo conversation, split by speaker (SE vs. Visitor). This is the raw input Claude uses for analysis.",
      position: "right"
    }
  ];

  /* ── Inject CSS (once) ────────────────────────────────────── */
  var styleId = "walkthrough-styles";
  if (!document.getElementById(styleId)) {
    var style = document.createElement("style");
    style.id = styleId;
    style.textContent = [
      /* Overlay backdrop */
      ".wt-backdrop {",
      "  position: fixed; inset: 0; z-index: 9000;",
      "  background: rgba(0,0,0,0.6);",
      "  transition: opacity 0.3s ease;",
      "  opacity: 0;",
      "}",
      ".wt-backdrop.active { opacity: 1; }",

      /* Highlighted element */
      ".wt-highlight {",
      "  position: relative;",
      "  z-index: 9001 !important;",
      "  box-shadow: 0 0 0 4px var(--accent, #58a6ff), 0 0 24px rgba(88,166,255,0.35);",
      "  border-radius: var(--radius, 10px);",
      "  transition: box-shadow 0.3s ease;",
      "}",

      /* Tooltip */
      ".wt-tooltip {",
      "  position: absolute; z-index: 9002;",
      "  background: #1c2333;",
      "  border: 1px solid #58a6ff;",
      "  border-radius: 10px;",
      "  padding: 20px 24px 16px;",
      "  max-width: 360px; min-width: 280px;",
      "  box-shadow: 0 8px 32px rgba(0,0,0,0.5);",
      "  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;",
      "  opacity: 0; transform: translateY(8px);",
      "  transition: opacity 0.3s ease, transform 0.3s ease;",
      "}",
      ".wt-tooltip.active { opacity: 1; transform: translateY(0); }",

      ".wt-tooltip .wt-step-num {",
      "  font-size: 11px; font-weight: 700; text-transform: uppercase;",
      "  letter-spacing: 0.08em; color: #58a6ff; margin-bottom: 6px;",
      "}",
      ".wt-tooltip .wt-title {",
      "  font-size: 16px; font-weight: 700; color: #e6edf3; margin-bottom: 8px;",
      "}",
      ".wt-tooltip .wt-body {",
      "  font-size: 13px; line-height: 1.6; color: #8b949e;",
      "}",
      ".wt-tooltip .wt-nav {",
      "  display: flex; justify-content: space-between; align-items: center;",
      "  margin-top: 16px; gap: 8px;",
      "}",
      ".wt-tooltip .wt-dots {",
      "  display: flex; gap: 6px;",
      "}",
      ".wt-tooltip .wt-dot {",
      "  width: 8px; height: 8px; border-radius: 50%;",
      "  background: #30363d; transition: background 0.2s;",
      "}",
      ".wt-tooltip .wt-dot.active { background: #58a6ff; }",
      ".wt-tooltip .wt-dot.done { background: #3fb950; }",

      ".wt-tooltip .wt-btn {",
      "  padding: 6px 16px; border-radius: 6px; border: none;",
      "  font-size: 13px; font-weight: 600; cursor: pointer;",
      "  transition: background 0.15s;",
      "}",
      ".wt-tooltip .wt-btn-prev {",
      "  background: #30363d; color: #e6edf3;",
      "}",
      ".wt-tooltip .wt-btn-prev:hover { background: #484f58; }",
      ".wt-tooltip .wt-btn-next {",
      "  background: #238636; color: #fff;",
      "}",
      ".wt-tooltip .wt-btn-next:hover { background: #2ea043; }",
      ".wt-tooltip .wt-btn-close {",
      "  background: transparent; color: #8b949e; padding: 6px 10px;",
      "}",
      ".wt-tooltip .wt-btn-close:hover { color: #e6edf3; }",

      /* Arrow (CSS triangle) */
      ".wt-tooltip::after {",
      "  content: ''; position: absolute;",
      "  width: 12px; height: 12px;",
      "  background: #1c2333; border: 1px solid #58a6ff;",
      "  transform: rotate(45deg);",
      "}",
      ".wt-tooltip.pos-bottom::after {",
      "  top: -7px; left: 24px;",
      "  border-right: none; border-bottom: none;",
      "}",
      ".wt-tooltip.pos-left::after {",
      "  right: -7px; top: 20px;",
      "  border-left: none; border-bottom: none;",
      "}",
      ".wt-tooltip.pos-right::after {",
      "  left: -7px; top: 20px;",
      "  border-right: none; border-top: none;",
      "}",
      ".wt-tooltip.pos-top::after {",
      "  bottom: -7px; left: 24px;",
      "  border-left: none; border-top: none;",
      "}",

      /* Walkthrough button in topbar */
      ".wt-start-btn {",
      "  display: inline-flex; align-items: center; gap: 6px;",
      "  padding: 5px 14px; border-radius: 6px;",
      "  border: 1px solid #58a6ff; background: #1f6feb22;",
      "  color: #58a6ff; font-size: 13px; font-weight: 600;",
      "  cursor: pointer; transition: background 0.15s, border-color 0.15s;",
      "}",
      ".wt-start-btn:hover { background: #1f6feb44; }",
      ".wt-start-btn svg { width: 14px; height: 14px; fill: currentColor; }"
    ].join("\n");
    document.head.appendChild(style);
  }

  /* ── Walkthrough Controller ───────────────────────────────── */
  function BoothWalkthrough() {
    this.currentStep = -1;
    this.backdrop = null;
    this.tooltip = null;
    this.activeSteps = [];
    this._onKeyDown = this._handleKey.bind(this);
    this._init();
  }

  BoothWalkthrough.prototype._init = function () {
    /* Insert the "Walkthrough" button into the topbar-right area */
    var topbarRight = document.querySelector(".topbar-right");
    if (!topbarRight) return;

    var btn = document.createElement("button");
    btn.className = "wt-start-btn";
    btn.innerHTML = '<svg viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg>' +
      "Walkthrough";
    btn.addEventListener("click", this.start.bind(this));
    topbarRight.insertBefore(btn, topbarRight.firstChild);
  };

  BoothWalkthrough.prototype.start = function () {
    /* Filter to only steps whose target element exists on the page */
    this.activeSteps = [];
    for (var i = 0; i < STEPS.length; i++) {
      var el = document.querySelector(STEPS[i].selector);
      if (el) this.activeSteps.push(STEPS[i]);
    }
    if (this.activeSteps.length === 0) return;

    /* Create backdrop */
    this.backdrop = document.createElement("div");
    this.backdrop.className = "wt-backdrop";
    document.body.appendChild(this.backdrop);
    /* Force reflow for transition */
    this.backdrop.offsetHeight;
    this.backdrop.classList.add("active");
    this.backdrop.addEventListener("click", this.stop.bind(this));

    /* Create tooltip container */
    this.tooltip = document.createElement("div");
    this.tooltip.className = "wt-tooltip";
    document.body.appendChild(this.tooltip);

    /* Keyboard nav */
    document.addEventListener("keydown", this._onKeyDown);

    this.currentStep = -1;
    this.next();
  };

  BoothWalkthrough.prototype.stop = function () {
    this._clearHighlight();
    if (this.backdrop) {
      this.backdrop.classList.remove("active");
      var bd = this.backdrop;
      setTimeout(function () { if (bd.parentNode) bd.parentNode.removeChild(bd); }, 300);
      this.backdrop = null;
    }
    if (this.tooltip) {
      this.tooltip.classList.remove("active");
      var tt = this.tooltip;
      setTimeout(function () { if (tt.parentNode) tt.parentNode.removeChild(tt); }, 300);
      this.tooltip = null;
    }
    document.removeEventListener("keydown", this._onKeyDown);
    this.currentStep = -1;
  };

  BoothWalkthrough.prototype.next = function () {
    if (this.currentStep >= this.activeSteps.length - 1) {
      this.stop();
      return;
    }
    this.currentStep++;
    this._showStep();
  };

  BoothWalkthrough.prototype.prev = function () {
    if (this.currentStep <= 0) return;
    this.currentStep--;
    this._showStep();
  };

  BoothWalkthrough.prototype._handleKey = function (e) {
    if (e.key === "Escape") { this.stop(); return; }
    if (e.key === "ArrowRight" || e.key === "Enter") { this.next(); return; }
    if (e.key === "ArrowLeft") { this.prev(); return; }
  };

  BoothWalkthrough.prototype._clearHighlight = function () {
    var prev = document.querySelector(".wt-highlight");
    if (prev) prev.classList.remove("wt-highlight");
  };

  BoothWalkthrough.prototype._showStep = function () {
    var step = this.activeSteps[this.currentStep];
    var el = document.querySelector(step.selector);
    if (!el) { this.next(); return; }

    /* Highlight */
    this._clearHighlight();
    el.classList.add("wt-highlight");

    /* Scroll element into view */
    el.scrollIntoView({ behavior: "smooth", block: "center" });

    /* Build tooltip content */
    var isLast = this.currentStep === this.activeSteps.length - 1;
    var isFirst = this.currentStep === 0;
    var self = this;

    var dotsHtml = "";
    for (var d = 0; d < this.activeSteps.length; d++) {
      var cls = "wt-dot";
      if (d < this.currentStep) cls += " done";
      if (d === this.currentStep) cls += " active";
      dotsHtml += '<span class="' + cls + '"></span>';
    }

    this.tooltip.className = "wt-tooltip pos-" + step.position;
    this.tooltip.innerHTML =
      '<div class="wt-step-num">Step ' + (this.currentStep + 1) + " of " + this.activeSteps.length + "</div>" +
      '<div class="wt-title">' + step.title + "</div>" +
      '<div class="wt-body">' + step.body + "</div>" +
      '<div class="wt-nav">' +
        '<div class="wt-dots">' + dotsHtml + "</div>" +
        '<div style="display:flex;gap:6px">' +
          (isFirst ? "" : '<button class="wt-btn wt-btn-prev" data-action="prev">Back</button>') +
          (isLast
            ? '<button class="wt-btn wt-btn-next" data-action="stop">Done</button>'
            : '<button class="wt-btn wt-btn-next" data-action="next">Next</button>') +
          '<button class="wt-btn wt-btn-close" data-action="stop">x</button>' +
        "</div>" +
      "</div>";

    /* Wire nav buttons */
    this.tooltip.querySelectorAll("[data-action]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        var action = btn.getAttribute("data-action");
        if (action === "next") self.next();
        else if (action === "prev") self.prev();
        else if (action === "stop") self.stop();
      });
    });

    /* Position tooltip relative to highlighted element */
    this._positionTooltip(el, step.position);

    /* Animate in */
    this.tooltip.classList.remove("active");
    this.tooltip.offsetHeight;
    this.tooltip.classList.add("active");
  };

  BoothWalkthrough.prototype._positionTooltip = function (el, position) {
    var rect = el.getBoundingClientRect();
    var tt = this.tooltip;
    var gap = 16;

    /* Reset so we can measure */
    tt.style.left = "0";
    tt.style.top = "0";
    var ttRect = tt.getBoundingClientRect();

    var left, top;

    switch (position) {
      case "bottom":
        left = rect.left + 12;
        top = rect.bottom + gap;
        break;
      case "top":
        left = rect.left + 12;
        top = rect.top - ttRect.height - gap;
        break;
      case "left":
        left = rect.left - ttRect.width - gap;
        top = rect.top + 8;
        break;
      case "right":
        left = rect.right + gap;
        top = rect.top + 8;
        break;
      default:
        left = rect.left;
        top = rect.bottom + gap;
    }

    /* Keep within viewport */
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    if (left + ttRect.width > vw - 16) left = vw - ttRect.width - 16;
    if (left < 16) left = 16;
    if (top + ttRect.height > vh - 16) top = vh - ttRect.height - 16;
    if (top < 16) top = 16;

    tt.style.position = "fixed";
    tt.style.left = left + "px";
    tt.style.top = top + "px";
  };

  /* ── Auto-init when DOM ready ─────────────────────────────── */
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () { new BoothWalkthrough(); });
  } else {
    /* Delay slightly to let session-viewer render its content */
    setTimeout(function () { new BoothWalkthrough(); }, 500);
  }

  window.BoothWalkthrough = BoothWalkthrough;
})();
